Repository 7Cav/7Cav-Alive, pull requests merged in 2020-01, with the labels that each got.

#21 Davidcit
  cScripts/CavFnc/CfgFunctions.hpp
  cScripts/CavFnc/cScripts_postInit.sqf
  cScripts/CavFnc/cScripts_preInit.sqf
  cScripts/CavFnc/functions/debug/fn_logError.sqf
  cScripts/CavFnc/functions/helpers/fn_exportLoadoutsToArsenal.sqf
  cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
  cScripts/CavFnc/functions/init/fn_initCuratorObjectPlaced.sqf
  cScripts/CavFnc/functions/init/fn_initModules.sqf
  cScripts/CavFnc/functions/init/fn_initStartupHint.sqf
  cScripts/CavFnc/functions/init/fn_initVehicle.sqf
  cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
  cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
  cScripts/CavFnc/functions/mission/fn_addJump.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
  cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
  cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
  cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf
  cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
  cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
  cScripts/CavFnc/functions/systems/fn_addHeal.sqf
  cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf
  cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
  cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
  cScripts/Loadouts/CfgLoadouts_tac2.hpp
  cScripts/Loadouts/script/CfgPoppy.hpp
  cScripts/Loadouts/script/functions/atomics/fn_replaceItems.sqf
  cba_settings.sqf
  mission.sqm
  scripts/arsenal.sqf
Labels: bug, enhancement

#23 ACE Medical Update
  cba_settings.sqf
Labels: BugFix

#72 Latest test
  cScripts/Loadouts/CfgLoadouts_tac2.hpp
  cba_settings.sqf
  mission.sqm
  scripts/vehicle/init/Base_Arsenal.sqf
Labels: BugFix

#73 Alive testing
  cScripts/Loadouts/CfgLoadouts_tac2.hpp
  cba_settings.sqf
  mission.sqm
  scripts/server/curator.sqf
  scripts/vehicle/init/Base_Arsenal.sqf
Labels: BugFix

#84 Hotfix
  cScripts/Loadouts/CfgLoadouts_tac2.hpp
  cba_settings.sqf
  description.ext
  mission.sqm
  tac2/fn_ammoBoxSpawner.sqf
Labels: BugFix, enhancement

#90 V5.1.2
  cScripts/CfgLoadouts.hpp
  cScripts/Loadouts/CfgLoadouts_tac2.hpp
  cScripts/Loadouts/script/CfgPoppy.hpp
  cba_settings.sqf
  description.ext
  mission.sqm
Labels: BugFix, enhancement

#98 Create LICENSE
  LICENSE
Labels: documentation

#110 USAF Removal
  cScripts/ViewingDistance/CfgFunctions.hpp
  cScripts/ViewingDistance/GUI.h
  cScripts/ViewingDistance/defines.h
  cScripts/ViewingDistance/fn_onChar.sqf
  cScripts/ViewingDistance/fn_onSavePressed.sqf
  cScripts/ViewingDistance/fn_onSaveSelectionChanged.sqf
  cScripts/ViewingDistance/fn_onSliderChanged.sqf
  cScripts/ViewingDistance/fn_onTerrainChanged.sqf
  cScripts/ViewingDistance/fn_openMenu.sqf
  cScripts/ViewingDistance/fn_openSaveManager.sqf
  cScripts/ViewingDistance/fn_stateTracker.fsm
  cScripts/ViewingDistance/fn_updateViewDistance.sqf
  description.ext
  mission.sqm
Labels: BugFix

#113 Fixing VCOM CBA Settings
  cScripts/CfgLoadouts.hpp
  cScripts/Loadouts/CfgLoadouts_tac2.hpp
  cba_settings.sqf
Labels: BugFix
