Repository 7Cav/7Cav-Alive, pull requests merged in 2020-03, with the labels that each got.

#162 Pull Request #2 Electric Boogaloo
  7Cav-Alive-WFW.Altis/cScripts/Loadouts/CfgLoadouts_Charlie.hpp
  7Cav-Alive.Altis/cScripts/Loadouts/CfgLoadouts_Charlie.hpp
  7Cav-Alive.Tanoa/cScripts/Loadouts/CfgLoadouts_Charlie.hpp
Labels: BugFix, enhancement

#172 5.4.1 Hotfix
  7Cav-Alive-WFW.Altis/cba_settings.sqf
  7Cav-Alive-WFW.Altis/description.ext
  7Cav-Alive-WFW.Altis/mission.sqm
  7Cav-Alive-WFW.Altis/scripts/vehicle/init/Base_StaticWeapon.sqf
  7Cav-Alive.Altis/cba_settings.sqf
  7Cav-Alive.Altis/description.ext
  7Cav-Alive.Altis/mission.sqm
  7Cav-Alive.Altis/scripts/vehicle/init/Base_StaticWeapon.sqf
  7Cav-Alive.Tanoa/cba_settings.sqf
  7Cav-Alive.Tanoa/description.ext
  7Cav-Alive.Tanoa/mission.sqm
  7Cav-Alive.Tanoa/scripts/vehicle/init/Base_StaticWeapon.sqf
Labels: BugFix, enhancement

#191 Davidcit tanoa bug fixes
  7Cav-Alive.Altis/cScripts/CavFnc/cScripts_postInit.sqf
  7Cav-Alive.Altis/cScripts/CavFnc/functions/init/fn_initDocuments.sqf
  7Cav-Alive.Altis/cScripts/CavFnc/functions/script_component.hpp
  7Cav-Alive.Altis/initServer.sqf
  7Cav-Alive.Altis/scripts/client/ammoBoxSpawner.sqf
  7Cav-Alive.Altis/tac2/fn_ammoBoxSpawner.sqf
  7Cav-Alive.Takistan/mission.sqm
  7Cav-Alive.Tanoa/mission.sqm
Labels: BugFix, enhancement

#192 medical ui overrides
  7Cav-Alive.Altis/cba_settings.sqf
Labels: BugFix

#199 ###URGENT### disable ace fragmentation
  7Cav-Alive.Altis/cba_settings.sqf
Labels: BugFix, enhancement

#196 WFW Persistence Update
  7Cav-Alive-WFW.Altis/mission.sqm
  7Cav-Alive.Altis/mission.sqm
Labels: BugFix

#204 WarFare Wednesday Update
  7Cav-Alive-WFW.Altis/mission.sqm
  7Cav-Alive.Altis/cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
  7Cav-Alive.Altis/description.ext
  7Cav-Alive.Altis/initServer.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_FOB.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMMTAmmo_Apollo.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMMTRepair_Apollo.sqf
Labels: BugFix, Discussion

#206 BoxSpawnerFix
  7Cav-Alive.Altis/description.ext
  7Cav-Alive.Altis/mission.sqm
  7Cav-Alive.Altis/scripts/client/ammoBoxSpawner.sqf
  7Cav-Alive.Takistan/mission.sqm
Labels: BugFix
