Repository 7Cav/7Cav-Alive, pull requests merged in 2020-04, with the labels that each got.

#234 missionEnd fix
  7Cav-Alive.Altis/scripts/client/missionEndStrongPoint.sqf
Labels: BugFix

#233 random bug-fixes
  7Cav-Alive.Altis/cba_settings.sqf
  7Cav-Alive.Altis/initServer.sqf
  7Cav-Alive.Altis/scripts/client/ammoBoxSpawner.sqf
Labels: BugFix

#240 PR #231 Electric Boogaloo
  7Cav-Alive.Takistan/mission.sqm
  7Cav-Alive.chernarus/mission.sqm
Labels: BugFix, Mission Related, New Msision, Script Related, enhancement

#237 Disable scripted respawn
  7Cav-Alive.Altis/initPlayerLocal.sqf
  7Cav-Alive.Altis/onPlayerRespawn.sqf
Labels: BugFix, enhancement

#239 Disable Respawn Functionality
  7Cav-Alive.Altis/scripts/vehicle/init/Base_A10.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Apache.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Arsenal.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Blackfish_Vehicle.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Blackhawk.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Boat.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Bobcat.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Bradley.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_C130.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Defense.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_FOB.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_FixedWing.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMMTAmmo_Apollo.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMMTRepair_Apollo.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMTTAmmo.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMTTFuel.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_HEMTTRepair.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Medical.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Radio.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Raven.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_SOV.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_SPG.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Saber.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Sparrow.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_Wheeled.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Base_WheeledArmed.sqf
  7Cav-Alive.Altis/scripts/vehicle/init/Random_Boat.sqf
Labels: BugFix, Script Related

#244 CSW Ammo Handling fix #3
  7Cav-Alive.Altis/cba_settings.sqf
Labels: BugFix
